version: "3"
services:
  web:
    container_name: app
    build: .
    ports:
      - "9000:9000"
    command: yarn dev
    environment:
      - NODE_ENV=dev
    restart: always
    volumes:
      - .:/app/
      - /app/node_modules
      - ./server/storage:/app/server/storage
    depends_on:
      - mongo
      - redis
    networks:
      - webnet
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ../data:/data/db
      - ./.docker/init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME="root"
      - MONGO_INITDB_ROOT_PASSWORD="root"
      - MONGO_INITDB_DATABASE="moment"
      - MONGO_INITDB_USERNAME="moment"
      - MONGO_INITDB_PASSWORD="fV=g#Dt/9JA=8{s^M?S;Wb|-"
    networks:
      - webnet
  redis: 
    container_name: 'redis'
    image: 'redis'
    volumes:
      - ./docker/images/redis/data:/data
    command: redis-server --requirepass $${REDIS_PASSWORD:U[^CbCFIYnc:eq$@EF#H}LC}      
    ports: 
      - "6379:6379"
    networks:
      - webnet        
networks:
  webnet:
    driver: bridge