version: "3"
services:
  web:
    container_name: app
    build: .
    ports:
      - "9000:9000"
    command: npm run dev
    environment:
      - NODE_ENV=dev
    volumes:
      - .:/app/
      - /app/node_modules
      - ./server/storage:/app/server/storage
    depends_on:
      - mongo
      - redis
    networks:
      - webnet
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
      - ./.docker/init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_USERNAME=test
      - MONGO_INITDB_PASSWORD=test
    networks:
      - webnet
  redis: 
    container_name: 'redis'
    image: 'redis'
    ports: 
      - "6379:6379"
    networks:
      - webnet        
networks:
  webnet:
    driver: bridge