name: Docker-compose CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          docker-compose build
          docker image prune
      - name: Deploy
        run: |
          docker-compose down
          docker-compose pull
          docker-compose up -d
