name: Docker-compose CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: docker-compose build
      - name: Decrypt CONFIG
        run: echo "${{ secrets.ENCRYPTED_CONFIG }}" | base64 --decode | openssl enc -d -aes-256-cbc -md sha256 -out config/dev.json -k "${{ secrets.ENCRYPTION_KEY }}"
      - name: Deploy
        run: |
          docker-compose down
          docker-compose pull
          docker-compose up -d
