name: Re-Deploy Contracts

on:
  workflow_dispatch:
    inputs:
      rollback:
        description: 'Trigger compile'
        required: true
        default: 'true'

jobs:
  rollback:
    runs-on: self-hosted

    steps:
      - name: Compile Contracts
        run: |
          docker-compose exec -i web npx hardhat --network sepolia run server/scripts/deploy.js
